export const MERCHANT_ESCROW_ABI = [
  {
    type: "constructor",
    inputs: [{ name: "initialAgent", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createOrder",
    inputs: [
      { name: "orderId", type: "bytes32", internalType: "bytes32" },
      { name: "merchant", type: "address", internalType: "address payable" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "credentialCommitment", type: "bytes32", internalType: "bytes32" },
      { name: "metadataURI", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "releasePayment",
    inputs: [{ name: "orderId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "releasePaymentDvP",
    inputs: [
      { name: "orderId", type: "bytes32", internalType: "bytes32" },
      { name: "physicalHandoverHash", type: "bytes32", internalType: "bytes32" },
      { name: "rwaAssetId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refundOrder",
    inputs: [
      { name: "orderId", type: "bytes32", internalType: "bytes32" },
      { name: "reason", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCircuitBreaker",
    inputs: [{ name: "_paused", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isPaused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrder",
    inputs: [{ name: "orderId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct MerchantEscrow.Order",
        components: [
          { name: "orderId", type: "bytes32", internalType: "bytes32" },
          { name: "buyer", type: "address", internalType: "address" },
          { name: "merchant", type: "address", internalType: "address payable" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "completedAt", type: "uint256", internalType: "uint256" },
          { name: "status", type: "uint8", internalType: "enum MerchantEscrow.OrderStatus" },
          { name: "credentialCommitment", type: "bytes32", internalType: "bytes32" },
          { name: "metadataURI", type: "string", internalType: "string" },
          { name: "physicalHandoverHash", type: "bytes32", internalType: "bytes32" },
          { name: "rwaAssetId", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedAgents",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setAuthorizedAgent",
    inputs: [
      { name: "agent", type: "address", internalType: "address" },
      { name: "authorized", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "OrderCreated",
    inputs: [
      { name: "orderId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "merchant", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "credentialCommitment", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentReleased",
    inputs: [
      { name: "orderId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "merchant", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "verifiedByAgent", type: "address", indexed: true, internalType: "address" },
      { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentReleasedDvP",
    inputs: [
      { name: "orderId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "merchant", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "physicalHandoverHash", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "rwaAssetId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "verifiedByAgent", type: "address", indexed: true, internalType: "address" },
      { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderRefunded",
    inputs: [
      { name: "orderId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "reason", type: "string", indexed: false, internalType: "string" },
      { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
] as const;

export const MERCHANT_RWA_ABI = [
  {
    type: "function",
    name: "mintAsset",
    inputs: [
      { name: "assetName", type: "string", internalType: "string" },
      { name: "assetType", type: "uint8", internalType: "enum MerchantRWA.AssetType" },
      { name: "merchant", type: "address", internalType: "address" },
      { name: "valuationHSK", type: "uint256", internalType: "uint256" },
      { name: "batchQuantity", type: "uint256", internalType: "uint256" },
      { name: "originLocation", type: "string", internalType: "string" },
      { name: "physicalBatchHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lockForDvP",
    inputs: [{ name: "assetId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeDvPHandover",
    inputs: [
      { name: "assetId", type: "uint256", internalType: "uint256" },
      { name: "buyer", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAsset",
    inputs: [{ name: "assetId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct MerchantRWA.PhysicalAsset",
        components: [
          { name: "assetId", type: "uint256", internalType: "uint256" },
          { name: "name", type: "string", internalType: "string" },
          { name: "assetType", type: "uint8", internalType: "enum MerchantRWA.AssetType" },
          { name: "originMerchant", type: "address", internalType: "address" },
          { name: "currentHolder", type: "address", internalType: "address" },
          { name: "valuationHSK", type: "uint256", internalType: "uint256" },
          { name: "batchQuantity", type: "uint256", internalType: "uint256" },
          { name: "originLocation", type: "string", internalType: "string" },
          { name: "physicalBatchHash", type: "bytes32", internalType: "bytes32" },
          { name: "status", type: "uint8", internalType: "enum MerchantRWA.AssetStatus" },
          { name: "mintedAt", type: "uint256", internalType: "uint256" },
          { name: "deliveredAt", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalAssets",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
] as const;
